---
updates:
  - directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
version: 2
