---
jobs:
  deploy:
    if: "${{ needs.release-please.outputs.release_created }}"
    name: "Deploy"
    needs:
      - "release-please"
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "actions/setup-node@v6"
        with:
          cache: "npm"
          node-version-file: ".tool-versions"
      - run: "npm ci --ignore-scripts --no-audit --no-fund --no-update-notifier"
      - run: "npm publish --provenance --access public"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"

  release-please:
    name: "Release"
    outputs:
      release_created: "${{ steps.release.outputs.release_created }}"
      tag_name: "${{ steps.release.outputs.tag_name }}"
    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - id: "release"
        uses: "googleapis/release-please-action@v4"
        with:
          config-file: ".github/release-please-config.json"
          manifest-file: ".github/release-please-manifest.json"

"on":
  push:
    branches:
      - "main"

name: "Release"
